name: SkyWars
version: ${project.version}
main: de.marvinleiers.skywars.SkyWars
api-version: 1.15
authors: [ Marvin2k0 ]
website: www.marvinleiers.de
commands:
  skywars:
    permission: skwars.admin
    aliases: [sw]

depend:
  - GrindMC-System
